// WARNING: this file is auto generated, any changes will be lost
import { createDesignComponent, CanvasStore } from "framer"
const canvas = CanvasStore.shared(); // CANVAS_DATA;
export const Add_Property_Room = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_i3lDMnP0W", {}, 375,60);
export const Add_Room_Element = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_CqWUZHHFN", {}, 375,46);
export const Button = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,BUTTON?:string}>(canvas, "id_D5uJ87ceI", {BUTTON:"string"}, 275,50);
export const CheckBox = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_Xx5YiIG5_", {}, 40,40);
export const Client_Quick_Info = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,TENANT?:string,Clieo_Eneti?:string,Number?:string,E_Mail_Address?:string}>(canvas, "id_RBHKVkfDB", {TENANT:"string",Clieo_Eneti:"string",Number:"string",E_Mail_Address:"string"}, 365,105);
export const Etage_Label = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,EG?:string}>(canvas, "id_uBwwCASyl", {EG:"string"}, 375,25);
export const Full_Screen_Confirmation = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,Deine_Angaben_wurden?:string,Movitation?:string,TENANT?:string,Clieo_Eneti?:string,Number?:string,E_Mail_Address?:string,TENANT?:string,Clieo_Eneti?:string,Number?:string,E_Mail_Address?:string,TENANT?:string,Clieo_Eneti?:string,Number?:string,E_Mail_Address?:string}>(canvas, "id_AnuJXjTjo", {Deine_Angaben_wurden:"string",Movitation:"string",TENANT:"string",Clieo_Eneti:"string",Number:"string",E_Mail_Address:"string",TENANT:"string",Clieo_Eneti:"string",Number:"string",E_Mail_Address:"string",TENANT:"string",Clieo_Eneti:"string",Number:"string",E_Mail_Address:"string"}, 375,667);
export const MenuPoint = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,OBJEKT_SUCHE?:string}>(canvas, "id_Ue_Nav4Oq", {OBJEKT_SUCHE:"string"}, 200,19);
export const Navigation_Bar = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_dHg46SlJi", {}, 375,45);
export const Property_Details = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_zLLnwtQwy", {}, 375,202);
export const Property_Instance_Title = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_yCO7KUMy9", {}, 375,140);
export const Property_Room_Element_Not_Checked = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,Name?:string}>(canvas, "id_QMOGwiLn7", {Name:"string"}, 375,45);
export const Property_Room_Switcher_Button = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_f_ccclK7W", {}, 375,60);
export const Responsability_Defect = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,Room?:string}>(canvas, "id_hKF6iGaHI", {Room:"string"}, 375,60);
export const Responsability_Defect_1 = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,Room?:string}>(canvas, "id_jUMEA8DES", {Room:"string"}, 375,60);
export const Room_Button_Unchecked = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,Room?:string}>(canvas, "id_B6ax_mKL6", {Room:"string"}, 375,60);
export const Room_Element_Unchecked = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,Name?:string}>(canvas, "id_NQUwGovOM", {Name:"string"}, 375,45);
export const Room_OK_Marker = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_IKPfOmwbv", {}, 70,60);
export const Schema_Small_Avatar = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_MFTj9J_9k", {}, 72,72);
export const Shot_Element = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_D9qK0G8ru", {}, 774,100);
export const StatusBar = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_i3eAyxxLa", {}, 375,44);
export const Total_Defect_Costs = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,Room?:string}>(canvas, "id_B9uczrye1", {Room:"string"}, 375,90);
